name = "SadderPack"
author = "Ozoku & Rubsad"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0bb7e42c8e2e8e41dbb6ab3d5dc8f511ebcbb05889000a8ad24ac58cdc4d9f0"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
