name = "SadderPack"
author = "Ozoku & Rubsad"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69bb0025a60449c212ee220974b874107636626bf3879a5926cdbc8b826cf0f6"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
